version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=clinic_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/clinic_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=180
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
    volumes:
      - ./backend/static:/app/static
    depends_on:
      - postgres
    restart: unless-stopped

  # Development Frontend Service (optional)
  frontend-dev:
    build:
      context: ./clinic-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./clinic-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  default:
    name: clinic-network 